# Site settings
author: Hillary Spitzer
title: 
header-img: img/home-bg.png
email: hspitzer2@gmail.com
copyright_name: Hillary Spitzer
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: HillarySpitzer
github_username:  hspitzer2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
